### ISSUE TITLE
Project category on godotengine asset-library

### ISSUE THREAD

**Issue by quentincaffeino** [jeremyz/godot-hexgrid#2]
I was browsing asset lib and saw your addon, it looks awesome. However I don't agree with the category you chose for it and I going to explain why.

When I saw category Addon I thought I can open asset lib in editor, find your addon and just click install. But then I saw the repo and saw that there is no addon in this project, this is a complete project. So if I would click install then it will put all those files inside my project potentially breaking it.

So I came to suggest to change category to `Template`. At least for now until it can't be used as an addon.

**Comment by jeremyz** [comment]
Hi, I honestly did not try to install it from the assetLib and did never use an addon.
I just tried it, the install panels shows the file conflicts (asking for overriding existing files with the same name) but it's not good enough.
Changing category to Template seems wrong to me, these are no templates, but classes that implement a logic.
Quickly checking what is done with other addons gives me the insight that I should put the said files in a addons/hexgrid/ subfolder. 
Am I right ??
If so, what about the demo, should I place it under addons/hexgrid/demo ?
many thanks !!

**Comment by quentincaffeino** [comment]
> Changing category to Template seems wrong to me, these are no templates, but classes that implement a logic.

Sorry, then I misunderstood your project)

> Quickly checking what is done with other addons gives me the insight that I should put the said files in a addons/hexgrid/ subfolder.

Basically - yes. That should be enough to get started.

If you would like to do something when person installs/uninstalls your addon (for example setup autoloads), then you need to add [plugin.cfg and plugin.gd](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html) to your addon directory.

> If so, what about the demo, should I place it under addons/hexgrid/demo ?

You can leave demo as is. This is really up to you.

Also when person installs your addon from in-editor assetlib he might not need some files. You can ignore them by creating [`.gitattributes`](https://www.git-scm.com/docs/gitattributes#_export_ignore) ([example](https://github.com/quentincaffeino/godot-console/blob/develop/.gitattributes)) file listing everything that end user doesn't need in order to use your addon.

Generally I try to keep my libs (not only for godot) as small and simple as possible. Because for example with godot, your demo code might get included in user exported game causing binary to get bigger which is not very good.

**Comment by jeremyz** [comment]
That should be cleaner, thanks a lot.
