### ISSUE TITLE
How to access the demo for this addon ?

### ISSUE THREAD

**Issue by Cwpute** [jeremyz/godot-hexgrid#3]
I'm not very used to github and i can't seem to download the demo game you provided with this addon. How should i do it ?
Maybe you could provide this demo as a separate asset in the asset library, marked as "Template" ? for people like who'd like to easily acess it through the Godot Asset store.

**Comment by jeremyz** [comment]
Hello, [.gitattributes](https://github.com/jeremyz/godot-hexgrid/blob/master/.gitattributes) defines some [gitattributes](https://git-scm.com/docs/gitattributes) which prevent all files that are not part of the library to be exported.
If you want to access the whole project, you'll have to clone it. Either by using the "Fork" button at the top right which will result of you having a fork of that project in your repositories.
Or by doing a manual clone from your machine : `git clone git@github.com:jeremyz/godot-hexgrid.git` 
Hope this helps.

**Comment by Cwpute** [comment]
It does, thanks ! :)

i still thank having the demo accessiblefrom the start or as a separate downloud in Godot's asset store is a good idea though ;)
