### ISSUE TITLE
How to use your scripts.

### ISSUE THREAD

**Issue by HugoEnzo** [jeremyz/godot-hexgrid#5]
Hey I was wondering how I would start and use the script on godot 4.1, I am fairly new to godot and was wondering how to get started with your library. I tried to add it to a addons folder but it didnt pop up as a plugin

**Comment by SkullDz** [comment]
Could you elaborate on what you meant by starting and using the script? 
You could attach a script to a node by right clicking the node that you want to script on the left hand window, then click on attach script. if thats what youre trying to find  out.

**Comment by HugoEnzo** [comment]
there are like 3 scripts, do I attach the hexgrid.gd to a node2d script. I would like a step by step readme as to what to do if that makes sense

**Comment by SkullDz** [comment]
Usually you only need to script the parent Node and then attach the hexgrid.gd to a node 2d and code it accordingly

**Comment by HugoEnzo** [comment]
do i need to have a hexagonal tilemap already?
like make it using the tilemap node on godot and then attach the script?

**Comment by jeremyz** [comment]
Hello, have you run the test project? This is a fairly complete example of how to use this little library.
