### ISSUE TITLE
Understanding how "Tank" inherits 

### ISSUE THREAD

**Issue by bukowa** [jeremyz/godot-hexgrid#6]
Hey first of all I have to mention that I have no understanding of the godot engine or documentation.
I tried firing the project to learn how some things work by looking at your project. If you think that it's not the proper place to ask this question please delete the issue.

While investigating how `Tank` works I cannot find any place in the code where it actually defines that the `Tank` is a `Piece`.
Maybe it is not? If not how does it knows how to move?

![whatisthisshit](https://github.com/jeremyz/godot-hexgrid/assets/38087302/95a44772-f2a3-4253-87fd-234a7a0bb509)

**Comment by jeremyz** [comment]
Hello, yes an issue is not the perect place to discuss code. You should have sent me an email.

In Unit.gd , second line : `extends Piece` so it inherits from Piece and defines the needed methods.

In Map.gd, I have 2 Vector : p0 and p1, respectively the position of the tank and the target (see `func reset()`).
If one of them is dragged (see `func on_click(pressed : bool)`), the corresponding position is updated accordingly and then `compute()` is called .

That's it ;)

For sure, this is not the way I would do it in a real game, but I wanted to keep Unit.gd as much clean as possible.

**Comment by bukowa** [comment]
> Hello, yes an issue is not the perect place to discuss code. You should have sent me an email.
> 
> In Unit.gd , second line : `extends Piece` so it inherits from Piece and defines the needed methods.
> 
> In Map.gd, I have 2 Vector : p0 and p1, respectively the position of the tank and the target (see `func reset()`). If one of them is dragged (see `func on_click(pressed : bool)`), the corresponding position is updated accordingly and then `compute()` is called .
> 
> That's it ;)
> 
> For sure, this is not the way I would do it in a real game, but I wanted to keep Unit.gd as much clean as possible.

Thank you for explanation. Maybe github discussion would be a better place then the question-answer would be publicly available.
